fooddiary/food/urls.py
from django.urls import path

from .views import index, details, FoodListView, FoodDetailView

app_name = "food"

urlpatterns = [
    # path('', index, name="index"),
    path('', FoodListView.as_view(), name="index"),
    # path('', FoodDetailView.as_view(), name="index"),
    path('<int:pk>', FoodDetailView.as_view(), name="details"),
    # path('<int:pk>', details, name="details"),
]

fooddiary/fooddiary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include("food.urls")),
    path('auth/', include("myauth.urls")),
]

fooddiary/myauth/urls.py
from django.urls import path

from .views import MeView, LoginView

app_name = "myauth"

urlpatterns = [
    path('me', MeView.as_view(), name="me"),
    path("login/", LoginView.as_view(), name="login"),
]

fooddiary/food/models.py
from django.db import models


class FoodKind(models.Model):
    name = models.CharField(max_length=32)
    desc = models.TextField(blank=True, null=False)

    def __str__(self):
        return self.name


class FoodTypeMeal(models.Model):
    class Meta:
        verbose_name_plural = "Meal"
    name = models.CharField(max_length=32)
    desc = models.TextField(blank=True, null=False)

    def __str__(self):
        return self.name


class FoodItem(models.Model):
    name = models.CharField(max_length=200)
    manufacturer = models.CharField(max_length=200)
    unit = models.CharField(max_length=20)
    calory = models.PositiveIntegerField()
    fat_contents = models.PositiveIntegerField()
    carb_contents = models.PositiveIntegerField()
    protein_contents = models.PositiveIntegerField()
    kind = models.ForeignKey(FoodKind, on_delete=models.PROTECT, related_name="fooditem")
    meal = models.ManyToManyField("food.FoodTypeMeal", related_name="food")

    def __str__(self):
        return self.name


class FoodProfile(models.Model):
    food = models.OneToOneField(
        FoodItem,
        on_delete=models.CASCADE,
        related_name="profile",
    )
    origin = models.CharField(max_length=64)

    def __str__(self):
        return f"Food {self.food.pk} from {self.origin}"

fooddiary/myauth/models.py
from typing import TYPE_CHECKING

from django.contrib.auth import get_user_model
from django.db import models

from django.contrib.auth.models import AbstractUser

UserModel: AbstractUser = get_user_model()

# class UserDetails(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
# class MyCustomUser(AbstractUser):
#     bio = models.TextField(blank=True)


class UserProfile(models.Model):
    user = models.OneToOneField(UserModel, on_delete=models.CASCADE, related_name="profile")
    bio = models.TextField(blank=True)

    if TYPE_CHECKING:
        objects: models.Manager

fooddiary/food/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from .models import FoodItem


def index(request: HttpRequest):

    # return HttpResponse(f"<h1>Hello path <code>{request.path}</code><h1>")
    context = {
        "food": FoodItem.objects.select_related("kind").order_by("kind").all()
    }
    return render(request=request, template_name="food/index.html", context=context)


class FoodListView(ListView):
    # model = FoodItem
    context_object_name = "foodlist"
    queryset = (
        FoodItem
        .objects
        .select_related("kind")
        .order_by("pk")
        .all()
    )


class FoodDetailView(DetailView):
    template_name = "food/details.html"
    context_object_name = "food"
    queryset = (
        FoodItem.objects.select_related("profile", "kind")
    )


def details(request: HttpRequest, pk: int):
    context = {
        "food": get_object_or_404(
            FoodItem.objects.select_related("profile", "kind"),
            pk=pk
        )
    }
    return render(request=request, template_name="food/details.html", context=context)

fooddiary/myauth/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpRequest
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    LoginView as LoginViewGeneric,
    LogoutView as LogoutViewGeneric,
)


class MeView(TemplateView):
    template_name = "myauth/me.html"


class LoginView(LoginViewGeneric):
    form_class = AuthenticationForm
    next_page = reverse_lazy("myauth:me")

fooddiary/food/templates/food/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            The title
        {% endblock %}
    </title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

  </head>
  <body>
  <div class="container">
{% block body %}
    <h1>Hello</h1>
{% endblock %}
  </div>
  </body>
</html>

fooddiary/food/templates/food/details.html
{% extends "food/base.html" %}

{% block title %}
    {{ food.name }} details
{% endblock %}

{% block body %}
    <h1>Food <strong>{{ food.name }}</strong></h1>
        <div>
            <p> {{ food.manufacturer }} </p>
        </div>
        <div>
        <h2>Profile:</h2>
            <div>
              <div class="row">
                <div class="col">
                  Origin:
                </div>
                <div class="col">
                  {{ food.profile.origin }}
                </div>
              </div>
            </div>
        </div>
<div>
      <h2>Meal:</h2>
        <ul class="list-group">
{#            {% for meal in fooditem.meal %}#}
            {% for meal in food.meal.all %}
            <li class="list-group-item">
            {{ meal.name }}
            </li>
            {% endfor %}
        </ul>
 </div>


  <div class="my-2">
    <a href="{% url 'food:index' %}">Back to food list</a>
  </div>
{% endblock %}

fooddiary/food/templates/food/fooditem_list.html
{% extends "food/base.html" %}

{% block title %}
    Food list
{% endblock %}

{% block body %}
    <h1>Food</h1>
        <ul class="list-group">
            {% for fooditem in object_list %}
            <li class="list-group-item">
            <a href="{% url 'food:details' fooditem.pk %}">{{ fooditem.name }} [{{ fooditem.kind }}]</a>
            </li>
            {% endfor %}
        </ul>
{% endblock %}

fooddiary/food/templates/food/index.html
{% extends "food/base.html" %}

{% block title %}
    Food list
{% endblock %}

{% block body %}
    <h1>Food</h1>
        <ul class="list-group">
            {% for fooditem in food %}
            <li class="list-group-item">
            <a href="{% url 'food:details' fooditem.pk %}">{{ fooditem.name }} [{{ fooditem.kind }}]</a>
            </li>
            {% endfor %}
        </ul>
{% endblock %}

fooddiary/myauth/templates/myauth/me.html
{% extends "food/base.html" %}

{% block title %}
    User info
{% endblock %}

{% block body %}
  <h1>Hello {% firstof user.first_name user.email user.username user %}</h1>
  <h3>Bio:</h3>
  <p>
    {% if user.profile.bio %}
      {{ user.profile.bio }}
    {% else %}
      <span>no bio</span>
    {% endif %}
  </p>
{% endblock %}